[manifest]
version = "0.1.0"
priority = 0 # Priority for loading the file

[[patches]]
[patches.pattern]
match_indent = true
pattern = "for _, v in ipairs(info_queue) do"
position = 'before'
target = 'functions/common_events.lua'
payload = '''
    if next(SMODS.find_card('j_wafflemod_fuzzy_pickle')) and card_type ~= 'Locked' and card_type ~= 'Undiscovered' then

        if card and card.has_attribute and card:has_attribute("reference") then
            if G.localization.descriptions.Other["r_" .. _c.key] ~= nil then
                info_queue[#info_queue + 1] = {key = "r_" .. _c.key, set = "Other"}
            else
                info_queue[#info_queue + 1] = {key = "r_generic", set = "Other"}
            end
        end

    end
'''
# big mcthankies to borb43 for providing this solution